### ISSUE TITLE
Node.js backward compatibility

### ISSUE THREAD

**Issue by Twelvelines** [qdrant/qdrant-js#22]
The application I am currently working on is deployed on [Render](https://render.com) server where they got only Node.js 14 on their free servers (at least for me). I am also seeking support on their side for any chance of upgrading Node but in the meantime I wonder is there any chance for Qdrant js client to have backward compatibility support for Node version previous than 18? 

```
error @qdrant/js-client-rest@1.2.0: The engine "node" is incompatible with this module. 
Expected version ">=18.0.0". Got "14.17.0"
```

For now I'll just tell Node to ```--ignore-engines```.

**Comment by Twelvelines** [comment]
Well this just in: actually I can't seem to use qdrant client under Node 14.17.0 because it cannot get the headers

```JSON
{
    "error": "Headers is not defined",
}
```

it might be related to the way the client is getting the headers for authentication, like described [here](https://stackoverflow.com/a/65355673). I might look into the source code again to be sure when I have the time, but for now, well, back to the good old trusty handle-request-by-oneself 😂

**Comment by Twelvelines** [comment]
My bad. The Render's support just contacted me that I could change the node version on the server as documented [here](https://render.com/docs/node-version), and this has been there from the start! Stupid me 😵

But I'll leave this thread for a while for the devs to close it if they deem this problem trivial at this moment.

**Comment by Rendez** [comment]
Since Node.js 17, the fetch API was available using a flag, e.g.: `node --experimental-fetch`. Though, this library works with Node 16 too, not sure if with 14 too or how far back, haven't tested. If you *must* use a previous version, polyfill `AbortController`, `AbortSignal` H`eaders`, `Request`, `Response` and `global.fetch`. It's something you can achieve with undici.js or node-fetch. Under the hood, Node 18 with native fetch uses undici.js (for now HTTP/1.1 until they bring us HTTP/2).
